version: '3'

services:
  db:
    image: postgres:${PG_VERSION}
    restart: always
    environment:
      POSTGRES_DB: crawlers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - ${PG_PORT}:5432

  pgadmin:
    image: chorss/docker-pgadmin4
    restart: always
    # IF PermissionError: [Errno 13] Permission denied: '/data/logs' ->
    # THAN Grant permission to the local folder [sudo chmod u=rwx,g=rwx,o=rwx ./pgadmin]
    volumes:
      - ./pgadmin:/data
    ports:
      - ${PG_ADMIN_PORT}:5050
    depends_on:
      - db

  prometheus:
    image: quay.io/prometheus/prometheus:${PROMETHEUS_VERSION}
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml

  # Microservices
  api_crawl_request:
    build:
      context: ./api_crawl_request
    restart: always
    # bind dev volume for hot reload
    volumes:
      - ./api_crawl_request/app:/app
    ports:
      - ${API_CRAWL_REQUEST_PORT}:8000
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - API_CRAWL_REQUEST_DB_URI=postgresql+asyncpg://postgres:postgres@db:5432/crawlers
