LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '0.0.0.0'
WEB_PORT: 8000

DB_URI: "postgresql+asyncpg://postgres:postgres@db:5432/crawlers"
