global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api_crawl_request'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'api_crawl_request:8000' ]
